//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrant
    {
        public Entrant()
        {
            this.EntrantEvents = new HashSet<EntrantEvent>();
            this.IndividualResults = new HashSet<IndividualResult>();
        }
    
        public int EntrantId { get; set; }
        public int RaceNumber { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<EntrantEvent> EntrantEvents { get; set; }
        public virtual ICollection<IndividualResult> IndividualResults { get; set; }
    }
}
