//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrantEvent
    {
        public int EntrantEventId { get; set; }
        public int EntrantId { get; set; }
        public int RaceId { get; set; }
        public string Gender { get; set; }
        public Nullable<int> RaceGroupTypeId { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Entrant Entrant { get; set; }
        public virtual Event Event { get; set; }
        public virtual Race Race { get; set; }
        public virtual RaceGroup RaceGroup { get; set; }
    }
}
