//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EntrantEvents = new HashSet<EntrantEvent>();
        }
    
        public int EventTypeId { get; set; }
        public string EventTypeName { get; set; }
    
        public virtual ICollection<EntrantEvent> EntrantEvents { get; set; }
    }
}
