//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualResult
    {
        public int IndividualResultId { get; set; }
        public Nullable<int> EntrantId { get; set; }
        public Nullable<int> RaceNumber { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<System.TimeSpan> OverallTime { get; set; }
        public Nullable<int> OverallRank { get; set; }
        public Nullable<System.TimeSpan> SwimTime { get; set; }
        public Nullable<int> SwimRank { get; set; }
        public Nullable<System.TimeSpan> Tran1Time { get; set; }
        public Nullable<int> Tran1Rank { get; set; }
        public Nullable<System.TimeSpan> BikeTime { get; set; }
        public Nullable<int> BikeRank { get; set; }
        public Nullable<System.TimeSpan> Tran2Time { get; set; }
        public Nullable<int> Tran2Rank { get; set; }
        public Nullable<System.TimeSpan> RunTime { get; set; }
        public Nullable<int> RunRank { get; set; }
        public string RaceId { get; set; }
    
        public virtual Entrant Entrant { get; set; }
    }
}
