//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.EntrantEvents = new HashSet<EntrantEvent>();
        }
    
        public int RaceId { get; set; }
        public Nullable<int> RaceDetailId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SeriesNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<EntrantEvent> EntrantEvents { get; set; }
        public virtual RaceDetail RaceDetail { get; set; }
    }
}
