//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRacePlace
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceDetail
    {
        public RaceDetail()
        {
            this.Races = new HashSet<Race>();
        }
    
        public int RaceDetailId { get; set; }
        public string DistanceDescription { get; set; }
        public string RaceDirector { get; set; }
        public string TimingResultsBy { get; set; }
        public string ResultsQuestionToName { get; set; }
        public string ResultsQuestionsToEmail { get; set; }
        public string RaceWebsiteUrl { get; set; }
    
        public virtual ICollection<Race> Races { get; set; }
    }
}
